#!/usr/bin/env node
/* =====================================================================
   build.mjs — assemble the modular src/ tree into the single, offline,
   double-click `steel_connection_tool.html` deliverable.

   No dependencies, no bundler: the output is one self-contained HTML file
   (vanilla JS + inline SVG) exactly as the spec requires. This script only
   concatenates the source modules — editing a connection in
   src/connections/ never touches another connection.

   Run:  node build.mjs   (or `npm run build`)
   ===================================================================== */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = dirname(fileURLToPath(import.meta.url));
const r = (...p) => readFileSync(join(ROOT, ...p), "utf8");
const OUT = "steel_connection_tool.html";

/* ---- the section database is the single source of truth for the data ----
   (uk_sections.json — embedded verbatim into the build, never duplicated). */
const sections = JSON.parse(r("uk_sections.json"));

/* ---- script assembly order ----
   1. shared "prerequisite" core modules (engine + data), in dependency order
   2. the GEO registry declaration lives at the end of 08-geometry.js
   3. every connection module (each isolated; order among them is irrelevant)
   4. the remaining core (validation, render orchestrator, UI, export, init)  */
const CORE_BEFORE = [
  "core/01-data-tables.js",
  "core/02-conn-meta.js",
  "core/03-section-utils.js",
  "core/04-controls.js",
  "core/05-state.js",
  "core/06-primitives.js",
  "core/07-render.js",
  "core/08-geometry.js",
];
const CORE_AFTER = [
  "core/20-validate.js",
  "core/21-orchestrator.js",
  "core/22-ui.js",
  "core/23-export.js",
  "core/24-init.js",
];

// every *.js in src/connections, sorted for a deterministic build
const CONNECTIONS = readdirSync(join(ROOT, "src", "connections"))
  .filter((f) => f.endsWith(".js"))
  .sort()
  .map((f) => join("connections", f));

const banner = (title) =>
  `/* ===== ${title} ${"=".repeat(Math.max(3, 64 - title.length))} */`;

const modules = [...CORE_BEFORE, ...CONNECTIONS, ...CORE_AFTER];

const script = [
  '"use strict";',
  "/* AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY.",
  "   Built from src/ by build.mjs (npm run build). Edit the modules in src/.",
  "   Parametric Steel Connection Detailing Tool — vanilla JS, single file.",
  "   Design basis: SS EN 1993-1-8, SSSS (Liew 2019), SCI P358/P363.",
  "   Phase 1: geometry + detailing-rule validation only (no capacity). */",
  "",
  banner("section database (from uk_sections.json, 149 UK sections)"),
  `const SECTIONS = ${JSON.stringify(sections)};`,
  "",
  ...modules.map((m) => `${banner(m)}\n${r("src", m).replace(/\s*$/, "")}`),
].join("\n");

/* ---- inject the assembled CSS + JS into the HTML shell ---- */
const html = r("src", "shell.html")
  .replace("<!--@STYLES@-->", () => r("src", "styles.css").replace(/\s*$/, ""))
  .replace("<!--@SCRIPTS@-->", () => script);

writeFileSync(join(ROOT, OUT), html.replace(/\s*$/, "") + "\n");
console.log(
  `Built ${OUT}: ${modules.length} modules ` +
    `(${CONNECTIONS.length} connections), ${sections.length} sections, ` +
    `${(html.length / 1024).toFixed(0)} KB.`
);
